// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"encoding/json"
	"time"

	"gorm.io/gorm"
)

const TableNameBusiness = "public.business"

// Business mapped from table <public.business>
type Business struct {
	ID                int64           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_business_list_base,priority:1;index:idx_business_primary_list,priority:1;index:idx_business_primary_verified_list,priority:1" json:"id"`
	PrimaryCategoryID int64           `gorm:"column:primary_category_id;type:bigint;not null;index:idx_business_primary_list,priority:2;index:idx_business_primary_verified_list,priority:3;comment:一级分类ID（冗余，用于聚合统计/首页）" json:"primary_category_id"` // 一级分类ID（冗余，用于聚合统计/首页）
	CategoryID        int64           `gorm:"column:category_id;type:bigint;not null;index:idx_business_category_id,priority:1;comment:二级分类ID（category_items.id，不加外键）" json:"category_id"`                                                            // 二级分类ID（category_items.id，不加外键）
	Title             string          `gorm:"column:title;type:character varying(150);not null;index:idx_business_title_trgm,priority:1" json:"title"`
	TitleEn           string          `gorm:"column:title_en;type:character varying(150);not null;index:idx_business_title_en_trgm,priority:1" json:"title_en"`
	IsVerified        *bool           `gorm:"column:is_verified;type:boolean;not null;index:idx_business_primary_verified_list,priority:2;index:idx_business_verified,priority:1;default:false" json:"is_verified"`
	SeoTitle          string          `gorm:"column:seo_title;type:character varying(200);not null" json:"seo_title"`
	SeoDesc           string          `gorm:"column:seo_desc;type:character varying(255);not null" json:"seo_desc"`
	SeoKeywords       string          `gorm:"column:seo_keywords;type:character varying(255);not null" json:"seo_keywords"`
	Content           string          `gorm:"column:content;type:text;not null" json:"content"`
	ContentJSON       json.RawMessage `gorm:"column:content_json;type:jsonb;not null;index:idx_business_content_json_gin,priority:1;default:{}" json:"content_json"`
	LogoURL           string          `gorm:"column:logo_url;type:character varying(255);not null" json:"logo_url"`
	BannerURL         string          `gorm:"column:banner_url;type:character varying(255);not null" json:"banner_url"`
	Website           string          `gorm:"column:website;type:character varying(255);not null" json:"website"`
	RegionLocationIds []int64         `gorm:"column:region_location_ids;type:bigint[];not null;index:idx_business_region_gin,priority:1;default:{};comment:服务覆盖城市ID数组（GIN过滤；规模大可迁移为 mapping 表）" json:"region_location_ids"` // 服务覆盖城市ID数组（GIN过滤；规模大可迁移为 mapping 表）
	GeoLocationIds    []int64         `gorm:"column:geo_location_ids;type:bigint[];not null;index:idx_business_geo_gin,priority:1;default:{};comment:服务覆盖区域ID数组（GIN过滤；规模大可迁移为 mapping 表）" json:"geo_location_ids"`          // 服务覆盖区域ID数组（GIN过滤；规模大可迁移为 mapping 表）
	IsOnsite          *bool           `gorm:"column:is_onsite;type:boolean;not null;default:false" json:"is_onsite"`
	IsLicensed        *bool           `gorm:"column:is_licensed;type:boolean;not null;default:false" json:"is_licensed"`
	IsInsured         *bool           `gorm:"column:is_insured;type:boolean;not null;default:false" json:"is_insured"`
	Experience        *int16          `gorm:"column:experience;type:smallint;not null;default:0" json:"experience"`
	IsFreeEstimates   *bool           `gorm:"column:is_free_estimates;type:boolean;not null;default:false" json:"is_free_estimates"`
	BusinessHours     string          `gorm:"column:business_hours;type:text;not null" json:"business_hours"`
	SupportedLang     []int16         `gorm:"column:supported_lang;type:smallint[];not null;default:{}" json:"supported_lang"`
	AttrFlat          json.RawMessage `gorm:"column:attr_flat;type:jsonb;not null;index:idx_business_attr_gin,priority:1;default:{};comment:用于过滤的扁平化属性，如 {\"wifi\":true,\"lang\":[\"zh\",\"en\"]}" json:"attr_flat"`                                                          // 用于过滤的扁平化属性，如 {"wifi":true,"lang":["zh","en"]}
	Display           json.RawMessage `gorm:"column:display;type:jsonb;not null;default:{};comment:前端展示特效配置 JSON（如卡片高亮/标签等）" json:"display"`                                                                                                                                  // 前端展示特效配置 JSON（如卡片高亮/标签等）
	Priority          *int32          `gorm:"column:priority;type:integer;not null;index:idx_business_list_base,priority:2;index:idx_business_primary_list,priority:3;index:idx_business_primary_verified_list,priority:4;default:0;comment:列表页权重（置顶/推荐/排序）" json:"priority"` // 列表页权重（置顶/推荐/排序）
	Status            *int16          `gorm:"column:status;type:smallint;not null;index:idx_business_list_base,priority:3;index:idx_business_primary_list,priority:4;index:idx_business_primary_verified_list,priority:5;default:1;comment:状态：1正常 2下线" json:"status"`         // 状态：1正常 2下线
	StatusReason      string          `gorm:"column:status_reason;type:character varying(255);not null" json:"status_reason"`
	CreatedAt         time.Time       `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_business_created,priority:1" json:"created_at"`
	UpdatedAt         time.Time       `gorm:"column:updated_at;type:timestamp with time zone;not null;index:idx_business_updated,priority:1;comment:更新时间（无触发器，需应用层更新）" json:"updated_at"` // 更新时间（无触发器，需应用层更新）
	DeletedAt         gorm.DeletedAt  `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_business_deleted_at,priority:1;comment:软删除时间（非空表示已删除）" json:"deleted_at"`          // 软删除时间（非空表示已删除）
}

// TableName Business's table name
func (*Business) TableName() string {
	return TableNameBusiness
}
