// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameBusinessPhone = "public.business_phones"

// BusinessPhone mapped from table <public.business_phones>
type BusinessPhone struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	BusinessID int64     `gorm:"column:business_id;type:bigint;not null;uniqueIndex:uniq_business_phones_primary,priority:1;index:idx_business_phones_bid,priority:1;comment:商家ID（不加外键）" json:"business_id"` // 商家ID（不加外键）
	LocationID *int64    `gorm:"column:location_id;type:bigint;not null;index:idx_business_phones_location_id,priority:1;default:0;comment:地址ID（business_locations.id，非必填）" json:"location_id"`              // 地址ID（business_locations.id，非必填）
	Phone      string    `gorm:"column:phone;type:character varying(30);not null" json:"phone"`
	ClickCount *int64    `gorm:"column:click_count;type:bigint;not null;default:0;comment:该电话点击次数（如高频更新可转为异步聚合）" json:"click_count"` // 该电话点击次数（如高频更新可转为异步聚合）
	IsPrimary  *bool     `gorm:"column:is_primary;type:boolean;not null;default:false;comment:是否主电话（每商家最多一个）" json:"is_primary"`     // 是否主电话（每商家最多一个）
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp with time zone;not null" json:"created_at"`
}

// TableName BusinessPhone's table name
func (*BusinessPhone) TableName() string {
	return TableNameBusinessPhone
}
