// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameBusinessLocation = "public.business_locations"

// BusinessLocation mapped from table <public.business_locations>
type BusinessLocation struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	BusinessID    int64     `gorm:"column:business_id;type:bigint;not null;uniqueIndex:uniq_business_locations_primary,priority:1;index:idx_business_locations_bid,priority:1;comment:商家ID（不加外键）" json:"business_id"` // 商家ID（不加外键）
	Street        string    `gorm:"column:street;type:character varying(255);not null;comment:街道地址" json:"street"`                                                                                                    // 街道地址
	Unit          string    `gorm:"column:unit;type:character varying(50);not null;comment:房间号/套间" json:"unit"`                                                                                                       // 房间号/套间
	CityName      string    `gorm:"column:city_name;type:character varying(100);not null;comment:城市名称" json:"city_name"`                                                                                              // 城市名称
	StateCode     string    `gorm:"column:state_code;type:character(2);not null;comment:州代码（如 CA）" json:"state_code"`                                                                                                 // 州代码（如 CA）
	ZipCode       string    `gorm:"column:zip_code;type:character varying(10);not null;comment:邮编" json:"zip_code"`                                                                                                   // 邮编
	Lat           *float64  `gorm:"column:lat;type:double precision;comment:纬度，可为空" json:"lat"`                                                                                                                       // 纬度，可为空
	Lng           *float64  `gorm:"column:lng;type:double precision;comment:经度，可为空" json:"lng"`                                                                                                                       // 经度，可为空
	Location      *string   `gorm:"column:location;type:geometry(Point,4326);index:idx_business_locations_geo,priority:1;comment:PostGIS POINT(4326)，由 lat/lng 自动生成" json:"location"`                                 // PostGIS POINT(4326)，由 lat/lng 自动生成
	BusinessHours string    `gorm:"column:business_hours;type:text;not null;comment:营业时间文本（后期可升级 JSON）" json:"business_hours"`                                                                                        // 营业时间文本（后期可升级 JSON）
	IsPrimary     *bool     `gorm:"column:is_primary;type:boolean;not null;default:false;comment:是否主展示地址（每商家最多一个）" json:"is_primary"`                                                                                 // 是否主展示地址（每商家最多一个）
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp with time zone;not null" json:"created_at"`
}

// TableName BusinessLocation's table name
func (*BusinessLocation) TableName() string {
	return TableNameBusinessLocation
}
