// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameBusinessReview = "public.business_reviews"

// BusinessReview mapped from table <public.business_reviews>
type BusinessReview struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                                                                                     // 主键ID
	BusinessID int64     `gorm:"column:business_id;type:bigint;not null;index:idx_business_reviews_business_rating,priority:1;index:idx_business_reviews_business_time,priority:1;comment:商家ID（business.id）" json:"business_id"` // 商家ID（business.id）
	UserID     *int64    `gorm:"column:user_id;type:bigint;not null;index:idx_business_reviews_user,priority:1;default:0;comment:用户ID（匿名可为0）" json:"user_id"`                                                                    // 用户ID（匿名可为0）
	Rating     int16     `gorm:"column:rating;type:smallint;not null;index:idx_business_reviews_business_rating,priority:2;comment:评分（1-5分）" json:"rating"`                                                                      // 评分（1-5分）
	Content    string    `gorm:"column:content;type:text;not null;comment:评论内容" json:"content"`                                                                                                                                  // 评论内容
	Status     *int16    `gorm:"column:status;type:smallint;not null;index:idx_business_reviews_status,priority:1;default:1;comment:状态：1正常 2隐藏 3审核中" json:"status"`                                                              // 状态：1正常 2隐藏 3审核中
	UpdatedAt  time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null" json:"updated_at"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_business_reviews_business_time,priority:2;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName BusinessReview's table name
func (*BusinessReview) TableName() string {
	return TableNameBusinessReview
}
