// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"github.com/shopspring/decimal"
)

const TableNameBusinessMetric = "public.business_metrics"

// BusinessMetric mapped from table <public.business_metrics>
type BusinessMetric struct {
	BusinessID        int64            `gorm:"column:business_id;type:bigint;primaryKey;comment:商家ID（不加外键）" json:"business_id"` // 商家ID（不加外键）
	ViewCount         *int64           `gorm:"column:view_count;type:bigint;not null;default:0" json:"view_count"`
	ClickCount        *int64           `gorm:"column:click_count;type:bigint;not null;default:0" json:"click_count"`
	PhoneClickCount   *int64           `gorm:"column:phone_click_count;type:bigint;not null;default:0" json:"phone_click_count"`
	WebsiteClickCount *int64           `gorm:"column:website_click_count;type:bigint;not null;default:0" json:"website_click_count"`
	RatingAvg         *decimal.Decimal `gorm:"column:rating_avg;type:numeric(3,2);not null;default:0" json:"rating_avg"`
	RatingCount       *int32           `gorm:"column:rating_count;type:integer;not null;default:0" json:"rating_count"`
	FavoriteCount     *int64           `gorm:"column:favorite_count;type:bigint;not null;default:0" json:"favorite_count"`
	ReviewCount       *int64           `gorm:"column:review_count;type:bigint;not null;default:0" json:"review_count"`
	Score             *decimal.Decimal `gorm:"column:score;type:numeric(12,4);not null;index:idx_business_metrics_score,priority:1;default:0;comment:排序分数快照（建议异步计算/刷新）" json:"score"` // 排序分数快照（建议异步计算/刷新）
	LastViewAt        *time.Time       `gorm:"column:last_view_at;type:timestamp with time zone" json:"last_view_at"`
	UpdatedAt         time.Time        `gorm:"column:updated_at;type:timestamp with time zone;not null;comment:更新时间（无触发器，需应用层更新）" json:"updated_at"` // 更新时间（无触发器，需应用层更新）
}

// TableName BusinessMetric's table name
func (*BusinessMetric) TableName() string {
	return TableNameBusinessMetric
}
