// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameBusinessMedium = "public.business_media"

// BusinessMedium mapped from table <public.business_media>
type BusinessMedium struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_business_media_business_sort,priority:2;comment:主键ID" json:"id"`                                                     // 主键ID
	BusinessID int64     `gorm:"column:business_id;type:bigint;not null;index:idx_business_media_business_sort,priority:1;index:idx_business_media_cover,priority:1;comment:商家ID（business.id）" json:"business_id"` // 商家ID（business.id）
	MediaType  int16     `gorm:"column:media_type;type:smallint;not null;index:idx_business_media_type,priority:1;comment:媒体类型：1图片 2视频" json:"media_type"`                                                         // 媒体类型：1图片 2视频
	URL        string    `gorm:"column:url;type:character varying(255);not null;comment:媒体原始URL" json:"url"`                                                                                                       // 媒体原始URL
	ThumbURL   string    `gorm:"column:thumb_url;type:character varying(255);not null;comment:缩略图URL" json:"thumb_url"`                                                                                            // 缩略图URL
	Sort       *int32    `gorm:"column:sort;type:integer;not null;index:idx_business_media_business_sort,priority:3;default:0;comment:排序值（越大越靠前）" json:"sort"`                                                     // 排序值（越大越靠前）
	IsCover    *bool     `gorm:"column:is_cover;type:boolean;not null;index:idx_business_media_cover,priority:2;default:false;comment:是否封面图" json:"is_cover"`                                                      // 是否封面图
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;comment:创建时间" json:"created_at"`                                                                                          // 创建时间
}

// TableName BusinessMedium's table name
func (*BusinessMedium) TableName() string {
	return TableNameBusinessMedium
}
