// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"github.com/shopspring/decimal"
)

const TableNameBusinessOrder = "public.business_orders"

// BusinessOrder mapped from table <public.business_orders>
type BusinessOrder struct {
	ID                int64            `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                                                                      // 主键ID
	UserID            int64            `gorm:"column:user_id;type:bigint;not null;index:idx_business_orders_user,priority:2;comment:用户ID（users.id）" json:"user_id"`                                                             // 用户ID（users.id）
	BusinessID        int64            `gorm:"column:business_id;type:bigint;not null;index:idx_business_orders_business,priority:1;comment:商户ID（business.id）" json:"business_id"`                                              // 商户ID（business.id）
	OrderNo           string           `gorm:"column:order_no;type:character varying(40);not null;uniqueIndex:uniq_business_orders_no,priority:1;comment:订单号（业务唯一）" json:"order_no"`                                            // 订单号（业务唯一）
	RegionLocationIds []int64          `gorm:"column:region_location_ids;type:bigint[];not null;default:{};comment:置顶城市ID列表（geo_location.id）" json:"region_location_ids"`                                                       // 置顶城市ID列表（geo_location.id）
	PrimaryCategoryID *int64           `gorm:"column:primary_category_id;type:bigint;not null;index:idx_business_orders_category,priority:2;default:0;comment:一级分类ID（category.id），0=通用" json:"primary_category_id"`             // 一级分类ID（category.id），0=通用
	CategoryID        *int64           `gorm:"column:category_id;type:bigint;not null;index:idx_business_orders_category,priority:1;default:0;comment:二级分类ID（category.id），0=通用" json:"category_id"`                             // 二级分类ID（category.id），0=通用
	DisplayKeys       []string         `gorm:"column:display_keys;type:text[];not null;default:{};comment:展示效果列表，例如：bold / red / special_card" json:"display_keys"`                                                             // 展示效果列表，例如：bold / red / special_card
	Days              int32            `gorm:"column:days;type:integer;not null;comment:统一购买时长（如 7/14/30/60 天）" json:"days"`                                                                                                    // 统一购买时长（如 7/14/30/60 天）
	TotalPrice        *decimal.Decimal `gorm:"column:total_price;type:numeric(12,2);not null;default:0;comment:订单总价" json:"total_price"`                                                                                        // 订单总价
	Status            *int16           `gorm:"column:status;type:smallint;not null;index:idx_business_orders_status,priority:1;default:1;comment:订单状态：1=待支付 2=已支付 3=已取消 4=已退款" json:"status"`                                   // 订单状态：1=待支付 2=已支付 3=已取消 4=已退款
	PaidAt            *time.Time       `gorm:"column:paid_at;type:timestamp with time zone;comment:支付时间" json:"paid_at"`                                                                                                        // 支付时间
	StartAt           *time.Time       `gorm:"column:start_at;type:timestamp with time zone;index:idx_business_orders_time,priority:2;comment:生效时间" json:"start_at"`                                                            // 生效时间
	EndAt             *time.Time       `gorm:"column:end_at;type:timestamp with time zone;index:idx_business_orders_time,priority:1;comment:结束时间（统一到期时间）" json:"end_at"`                                                        // 结束时间（统一到期时间）
	CreatedAt         time.Time        `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_business_orders_business,priority:2;index:idx_business_orders_user,priority:1;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt         time.Time        `gorm:"column:updated_at;type:timestamp with time zone;not null;comment:更新时间（应用层维护）" json:"updated_at"`                                                                                  // 更新时间（应用层维护）
}

// TableName BusinessOrder's table name
func (*BusinessOrder) TableName() string {
	return TableNameBusinessOrder
}
