// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameBusinessPin = "public.business_pins"

// BusinessPin mapped from table <public.business_pins>
type BusinessPin struct {
	ID                int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                                                       // 主键ID
	BusinessID        int64      `gorm:"column:business_id;type:bigint;not null;index:idx_business_pins_business,priority:1;comment:商户ID（business.id）" json:"business_id"`                                 // 商户ID（business.id）
	PinType           int16      `gorm:"column:pin_type;type:smallint;not null;comment:置顶类型：1=城市置顶 2=一级分类置顶 3=二级分类置顶" json:"pin_type"`                                                                     // 置顶类型：1=城市置顶 2=一级分类置顶 3=二级分类置顶
	CityID            *int64     `gorm:"column:city_id;type:bigint;not null;index:idx_business_pins_lookup,priority:2;default:0;comment:显示城市ID（geo_location.id），0=不限制城市" json:"city_id"`                   // 显示城市ID（geo_location.id），0=不限制城市
	PrimaryCategoryID *int64     `gorm:"column:primary_category_id;type:bigint;not null;index:idx_business_pins_lookup,priority:3;default:0;comment:一级分类ID（category.id），0=不限制" json:"primary_category_id"` // 一级分类ID（category.id），0=不限制
	CategoryID        *int64     `gorm:"column:category_id;type:bigint;not null;index:idx_business_pins_lookup,priority:1;default:0;comment:二级分类ID（category.id），0=不限制" json:"category_id"`                 // 二级分类ID（category.id），0=不限制
	Weight            *int32     `gorm:"column:weight;type:integer;not null;index:idx_business_pins_lookup,priority:5;default:0;comment:置顶权重值（越大越靠前，不同置顶类型可定义不同策略）" json:"weight"`                         // 置顶权重值（越大越靠前，不同置顶类型可定义不同策略）
	StartAt           *time.Time `gorm:"column:start_at;type:timestamp with time zone;not null;default:now();comment:置顶开始时间" json:"start_at"`                                                              // 置顶开始时间
	EndAt             time.Time  `gorm:"column:end_at;type:timestamp with time zone;not null;index:idx_business_pins_time,priority:1;comment:置顶结束时间" json:"end_at"`                                        // 置顶结束时间
	Status            *int16     `gorm:"column:status;type:smallint;not null;index:idx_business_pins_lookup,priority:4;default:1;comment:状态：1=启用 0=禁用（用于临时下线置顶）" json:"status"`                            // 状态：1=启用 0=禁用（用于临时下线置顶）
	CreatedAt         time.Time  `gorm:"column:created_at;type:timestamp with time zone;not null;comment:创建时间" json:"created_at"`                                                                          // 创建时间
	UpdatedAt         time.Time  `gorm:"column:updated_at;type:timestamp with time zone;not null;comment:更新时间（应用层维护）" json:"updated_at"`                                                                   // 更新时间（应用层维护）
}

// TableName BusinessPin's table name
func (*BusinessPin) TableName() string {
	return TableNameBusinessPin
}
