// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"encoding/json"
	"time"
)

const TableNameCategory = "public.category"

// Category mapped from table <public.category>
type Category struct {
	ID          int64           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ParentID    *int64          `gorm:"column:parent_id;type:bigint;not null;index:idx_category_parent_active_priority,priority:2;default:0;comment:父级ID：0=一级分类，非0=子分类（指向 category.id，不加外键）" json:"parent_id"`       // 父级ID：0=一级分类，非0=子分类（指向 category.id，不加外键）
	Slug        string          `gorm:"column:slug;type:character varying(150);not null;comment:SEO slug（建议同一 parent_id 下唯一）" json:"slug"`                                                                           // SEO slug（建议同一 parent_id 下唯一）
	Title       string          `gorm:"column:title;type:character varying(100);not null;comment:分类展示名称" json:"title"`                                                                                               // 分类展示名称
	SeoTitle    string          `gorm:"column:seo_title;type:character varying(150);not null;comment:SEO标题" json:"seo_title"`                                                                                        // SEO标题
	SeoDesc     string          `gorm:"column:seo_desc;type:text;not null;comment:SEO描述" json:"seo_desc"`                                                                                                            // SEO描述
	SeoKeywords string          `gorm:"column:seo_keywords;type:character varying(255);not null;comment:SEO关键词（可选，逗号分隔）" json:"seo_keywords"`                                                                        // SEO关键词（可选，逗号分隔）
	HasChildren *bool           `gorm:"column:has_children;type:boolean;not null;default:false;comment:是否有子分类（冗余字段，便于快速判断）" json:"has_children"`                                                                     // 是否有子分类（冗余字段，便于快速判断）
	IsHome      *bool           `gorm:"column:is_home;type:boolean;not null;index:idx_category_home,priority:1;default:false;comment:是否首页展示（一般一级分类使用）" json:"is_home"`                                               // 是否首页展示（一般一级分类使用）
	IsActive    *bool           `gorm:"column:is_active;type:boolean;not null;index:idx_category_parent_active_priority,priority:1;default:false;comment:是否启用" json:"is_active"`                                     // 是否启用
	IsOnsite    *bool           `gorm:"column:is_onsite;type:boolean;not null;default:false;comment:是否支持上门服务（一般二级分类使用）" json:"is_onsite"`                                                                            // 是否支持上门服务（一般二级分类使用）
	IsCallFirst *bool           `gorm:"column:is_call_first;type:boolean;not null;default:false;comment:是否提示用户先电话联系" json:"is_call_first"`                                                                           // 是否提示用户先电话联系
	Attributes  json.RawMessage `gorm:"column:attributes;type:jsonb;not null;default:{};comment:JSON Schema 属性配置（一级=属性定义，二级=具体属性）" json:"attributes"`                                                                // JSON Schema 属性配置（一级=属性定义，二级=具体属性）
	Priority    *int32          `gorm:"column:priority;type:integer;not null;index:idx_category_home,priority:2;index:idx_category_parent_active_priority,priority:3;default:0;comment:展示权重（越大越靠前）" json:"priority"` // 展示权重（越大越靠前）
	CreatedAt   time.Time       `gorm:"column:created_at;type:timestamp with time zone;not null;comment:创建时间" json:"created_at"`                                                                                     // 创建时间
	UpdatedAt   time.Time       `gorm:"column:updated_at;type:timestamp with time zone;not null;comment:更新时间（应用层维护）" json:"updated_at"`                                                                              // 更新时间（应用层维护）
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
