// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameDailyPost = "public.daily_posts"

// DailyPost mapped from table <public.daily_posts>
type DailyPost struct {
	ID               int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RegionLocationID *int64     `gorm:"column:region_location_id;type:bigint;not null;index:idx_daily_posts_geo_location_status_publish,priority:2;default:0;comment:区域ID，0=通用内容" json:"region_location_id"` // 区域ID，0=通用内容
	Title            string     `gorm:"column:title;type:character varying(200);not null;index:idx_daily_posts_title_trgm,priority:1;comment:文章标题" json:"title"`                                             // 文章标题
	Content          string     `gorm:"column:content;type:text;not null;comment:正文内容" json:"content"`                                                                                                       // 正文内容
	ContentRaw       string     `gorm:"column:content_raw;type:text;not null" json:"content_raw"`
	CoverImage       string     `gorm:"column:cover_image;type:character varying(255);not null;comment:封面图URL" json:"cover_image"` // 封面图URL
	Slug             string     `gorm:"column:slug;type:character varying(150);not null" json:"slug"`
	SeoTitle         string     `gorm:"column:seo_title;type:character varying(200);not null" json:"seo_title"`
	SeoDesc          string     `gorm:"column:seo_desc;type:character varying(255);not null" json:"seo_desc"`
	SeoKeywords      string     `gorm:"column:seo_keywords;type:character varying(255);not null" json:"seo_keywords"`
	Status           *int16     `gorm:"column:status;type:smallint;not null;index:idx_daily_posts_geo_location_status_publish,priority:3;default:1;comment:状态：1=发布 0=草稿" json:"status"`                         // 状态：1=发布 0=草稿
	ClickCount       *int64     `gorm:"column:click_count;type:bigint;not null;default:0;comment:浏览量统计" json:"click_count"`                                                                                     // 浏览量统计
	PublishedAt      *time.Time `gorm:"column:published_at;type:timestamp with time zone;not null;index:idx_daily_posts_geo_location_status_publish,priority:1;default:now();comment:发布时间" json:"published_at"` // 发布时间
	CreatedAt        time.Time  `gorm:"column:created_at;type:timestamp with time zone;not null" json:"created_at"`
	UpdatedAt        time.Time  `gorm:"column:updated_at;type:timestamp with time zone;not null" json:"updated_at"`
}

// TableName DailyPost's table name
func (*DailyPost) TableName() string {
	return TableNameDailyPost
}
