// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameDevice = "public.devices"

// Device mapped from table <public.devices>
type Device struct {
	Token          string     `gorm:"column:token;type:character varying(4096);primaryKey" json:"token"`
	Platform       string     `gorm:"column:platform;type:character varying(16);not null" json:"platform"`
	InstallationID string     `gorm:"column:installation_id;type:character varying(128);not null;index:idx_devices_installation_id,priority:1" json:"installation_id"`
	Enabled        *bool      `gorm:"column:enabled;type:boolean;not null;index:idx_devices_enabled,priority:1;default:true" json:"enabled"`
	LastSeenAt     *time.Time `gorm:"column:last_seen_at;type:timestamp with time zone" json:"last_seen_at"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
}

// TableName Device's table name
func (*Device) TableName() string {
	return TableNameDevice
}
