// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameGeoLocation = "public.geo_location"

// GeoLocation mapped from table <public.geo_location>
type GeoLocation struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ParentID  *int64    `gorm:"column:parent_id;type:bigint;not null;uniqueIndex:uniq_geo_location_slug,priority:1;index:idx_geo_location_parent,priority:1;index:idx_geo_location_parent_active_priority,priority:2;default:0;comment:父级ID：0=州（State），非0=城市（geo_location）" json:"parent_id"` // 父级ID：0=州（State），非0=城市（geo_location）
	Slug      string    `gorm:"column:slug;type:character varying(150);not null;uniqueIndex:uniq_geo_location_slug,priority:2;index:idx_geo_location_parent_active_priority,priority:4;comment:URL路径标识（全局唯一），如 la, ny" json:"slug"`                                                           // URL路径标识（全局唯一），如 la, ny
	Title     string    `gorm:"column:title;type:character varying(50);not null;comment:中文名称" json:"title"`                                                                                                                                                                                   // 中文名称
	TitleEn   string    `gorm:"column:title_en;type:character varying(50);not null;comment:英文名称" json:"title_en"`                                                                                                                                                                             // 英文名称
	StateCode string    `gorm:"column:state_code;type:character(2);not null;comment:州缩写（CA/NY...）" json:"state_code"`                                                                                                                                                                         // 州缩写（CA/NY...）
	IsActive  *bool     `gorm:"column:is_active;type:boolean;not null;index:idx_geo_location_active,priority:1;index:idx_geo_location_parent_active_priority,priority:1;default:false;comment:是否展示/开放" json:"is_active"`                                                                      // 是否展示/开放
	Level     *int16    `gorm:"column:level;type:smallint;not null;index:idx_geo_location_level,priority:1;default:1;comment:层级：1=大区 2=商圈 3=城市" json:"level"`                                                                                                                                 // 层级：1=大区 2=商圈 3=城市
	Priority  *int32    `gorm:"column:priority;type:integer;not null;index:idx_geo_location_parent_active_priority,priority:3;default:0;comment:展示权重（越大越靠前）" json:"priority"`                                                                                                                 // 展示权重（越大越靠前）
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;comment:创建时间" json:"created_at"`                                                                                                                                                                      // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;comment:更新时间（无触发器，需应用层更新）" json:"updated_at"`                                                                                                                                                         // 更新时间（无触发器，需应用层更新）
}

// TableName GeoLocation's table name
func (*GeoLocation) TableName() string {
	return TableNameGeoLocation
}
