// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameGuide = "public.guide"

// Guide mapped from table <public.guide>
type Guide struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RegionLocationID *int64    `gorm:"column:region_location_id;type:bigint;not null;index:idx_guide_geo_location_category_status_created,priority:3;index:idx_guide_geo_location_status_created,priority:2;default:0;comment:区域ID，0=通用内容" json:"region_location_id"` // 区域ID，0=通用内容
	GuideCategoryID  *int64    `gorm:"column:guide_category_id;type:bigint;not null;index:idx_guide_category_status_created,priority:2;index:idx_guide_geo_location_category_status_created,priority:2;default:0;comment:指南分类ID" json:"guide_category_id"`            // 指南分类ID
	Title            string    `gorm:"column:title;type:character varying(200);not null;index:idx_guide_title_trgm,priority:1;comment:中文标题" json:"title"`                                                                                                             // 中文标题
	TitleEn          string    `gorm:"column:title_en;type:character varying(150);not null;comment:英文标题" json:"title_en"`                                                                                                                                             // 英文标题
	Content          string    `gorm:"column:content;type:text;not null;comment:正文内容" json:"content"`                                                                                                                                                                 // 正文内容
	ContentRaw       string    `gorm:"column:content_raw;type:text;not null" json:"content_raw"`
	CoverImage       string    `gorm:"column:cover_image;type:character varying(255);not null;comment:封面图片" json:"cover_image"` // 封面图片
	Slug             string    `gorm:"column:slug;type:character varying(150);not null" json:"slug"`
	SeoTitle         string    `gorm:"column:seo_title;type:character varying(200);not null" json:"seo_title"`
	SeoDesc          string    `gorm:"column:seo_desc;type:character varying(255);not null" json:"seo_desc"`
	SeoKeywords      string    `gorm:"column:seo_keywords;type:character varying(255);not null" json:"seo_keywords"`
	Status           *int16    `gorm:"column:status;type:smallint;not null;index:idx_guide_category_status_created,priority:3;index:idx_guide_geo_location_category_status_created,priority:4;index:idx_guide_geo_location_status_created,priority:3;default:1;comment:状态：1=上线" json:"status"`            // 状态：1=上线
	ClickCount       *int64    `gorm:"column:click_count;type:bigint;not null;default:0;comment:点击量" json:"click_count"`                                                                                                                                                                                  // 点击量
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_guide_category_status_created,priority:1;index:idx_guide_geo_location_category_status_created,priority:1;index:idx_guide_geo_location_status_created,priority:1;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt        time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;comment:更新时间" json:"updated_at"`                                                                                                                                                                           // 更新时间
}

// TableName Guide's table name
func (*Guide) TableName() string {
	return TableNameGuide
}
