// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameGuideCategory = "public.guide_category"

// GuideCategory mapped from table <public.guide_category>
type GuideCategory struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Title       string    `gorm:"column:title;type:character varying(100);not null;comment:中文分类名称" json:"title"`       // 中文分类名称
	TitleEn     string    `gorm:"column:title_en;type:character varying(150);not null;comment:英文分类名称" json:"title_en"` // 英文分类名称
	Slug        string    `gorm:"column:slug;type:character varying(150);not null;comment:分类SEO slug" json:"slug"`     // 分类SEO slug
	SeoTitle    string    `gorm:"column:seo_title;type:character varying(200);not null" json:"seo_title"`
	SeoDesc     string    `gorm:"column:seo_desc;type:character varying(255);not null" json:"seo_desc"`
	SeoKeywords string    `gorm:"column:seo_keywords;type:character varying(255);not null" json:"seo_keywords"`
	IsActive    *bool     `gorm:"column:is_active;type:boolean;not null;index:idx_guide_category_is_active_priority,priority:1;default:true" json:"is_active"`
	CategoryIds []int64   `gorm:"column:category_ids;type:bigint[];not null;default:{}" json:"category_ids"`
	Priority    *int32    `gorm:"column:priority;type:integer;not null;index:idx_guide_category_is_active_priority,priority:2;default:0;comment:业务排序权重" json:"priority"` // 业务排序权重
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp with time zone;not null" json:"created_at"`
}

// TableName GuideCategory's table name
func (*GuideCategory) TableName() string {
	return TableNameGuideCategory
}
