// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameNavCategory = "public.nav_category"

// NavCategory mapped from table <public.nav_category>
type NavCategory struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Title       string    `gorm:"column:title;type:character varying(50);not null" json:"title"`
	Slug        string    `gorm:"column:slug;type:character varying(150);not null;comment:导航分类 slug（唯一）" json:"slug"` // 导航分类 slug（唯一）
	SeoTitle    string    `gorm:"column:seo_title;type:character varying(150);not null" json:"seo_title"`
	SeoDesc     string    `gorm:"column:seo_desc;type:text;not null" json:"seo_desc"`
	SeoKeywords string    `gorm:"column:seo_keywords;type:character varying(255);not null" json:"seo_keywords"`
	Icon        string    `gorm:"column:icon;type:character varying(100);not null;comment:图标标识（可为 icon key 或 URL）" json:"icon"` // 图标标识（可为 icon key 或 URL）
	Priority    *int32    `gorm:"column:priority;type:integer;not null;index:idx_nav_category_list,priority:2;default:0" json:"priority"`
	IsActive    *bool     `gorm:"column:is_active;type:boolean;not null;index:idx_nav_category_list,priority:1;default:true" json:"is_active"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp with time zone;not null" json:"created_at"`
}

// TableName NavCategory's table name
func (*NavCategory) TableName() string {
	return TableNameNavCategory
}
