// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameNavSite = "public.nav_sites"

// NavSite mapped from table <public.nav_sites>
type NavSite struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RegionLocationID *int64    `gorm:"column:region_location_id;type:bigint;not null;index:idx_nav_sites_list,priority:4;default:0;comment:适用城市ID（geo_location.id），0表示通用" json:"region_location_id"` // 适用城市ID（geo_location.id），0表示通用
	CategoryID       int64     `gorm:"column:category_id;type:bigint;not null;index:idx_nav_sites_list,priority:1;comment:导航分类ID（不加外键）" json:"category_id"`                                          // 导航分类ID（不加外键）
	Title            string    `gorm:"column:title;type:character varying(100);not null" json:"title"`
	URL              string    `gorm:"column:url;type:character varying(255);not null" json:"url"`
	LogoURL          string    `gorm:"column:logo_url;type:character varying(255);not null" json:"logo_url"`
	Description      string    `gorm:"column:description;type:character varying(255);not null" json:"description"`
	IsRecommend      *bool     `gorm:"column:is_recommend;type:boolean;not null;default:false" json:"is_recommend"`
	IsHome           *bool     `gorm:"column:is_home;type:boolean;not null;index:idx_nav_sites_home,priority:1;default:false;comment:是否首页展示" json:"is_home"` // 是否首页展示
	IsActive         *bool     `gorm:"column:is_active;type:boolean;not null;index:idx_nav_sites_list,priority:2;default:true" json:"is_active"`
	Priority         *int32    `gorm:"column:priority;type:integer;not null;index:idx_nav_sites_home,priority:2;index:idx_nav_sites_list,priority:3;default:0" json:"priority"`
	ClickCount       *int64    `gorm:"column:click_count;type:bigint;not null;default:0;comment:点击计数（如高频建议异步聚合）" json:"click_count"` // 点击计数（如高频建议异步聚合）
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp with time zone;not null" json:"created_at"`
}

// TableName NavSite's table name
func (*NavSite) TableName() string {
	return TableNameNavSite
}
