// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"encoding/json"
	"time"
)

const TableNamePricingRule = "public.pricing_rules"

// PricingRule mapped from table <public.pricing_rules>
type PricingRule struct {
	ID                int64           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	PriceType         int16           `gorm:"column:price_type;type:smallint;not null;index:idx_pricing_match,priority:5;comment:价格类型：1展示类 2置顶类" json:"price_type"`                         // 价格类型：1展示类 2置顶类
	PinType           *int16          `gorm:"column:pin_type;type:smallint;not null;index:idx_pricing_match,priority:4;default:0;comment:置顶类型：0非置顶 1城市置顶 2一级分类置顶 3二级分类置顶" json:"pin_type"`  // 置顶类型：0非置顶 1城市置顶 2一级分类置顶 3二级分类置顶
	CityID            *int64          `gorm:"column:city_id;type:bigint;not null;index:idx_pricing_match,priority:2;default:0;comment:城市ID（0=通用）" json:"city_id"`                           // 城市ID（0=通用）
	PrimaryCategoryID *int64          `gorm:"column:primary_category_id;type:bigint;not null;index:idx_pricing_match,priority:6;default:0;comment:一级分类ID（0=通用）" json:"primary_category_id"` // 一级分类ID（0=通用）
	CategoryID        *int64          `gorm:"column:category_id;type:bigint;not null;index:idx_pricing_match,priority:1;default:0;comment:二级分类ID（0=通用）" json:"category_id"`                 // 二级分类ID（0=通用）
	Title             string          `gorm:"column:title;type:character varying(100);not null" json:"title"`
	DisplayKey        string          `gorm:"column:display_key;type:character varying(30);not null" json:"display_key"`
	PriceConfig       json.RawMessage `gorm:"column:price_config;type:jsonb;not null;index:idx_pricing_config_gin,priority:1;default:{};comment:价格配置JSON：支持价格、时长、货币、权重等扩展字段" json:"price_config"` // 价格配置JSON：支持价格、时长、货币、权重等扩展字段
	IsActive          *bool           `gorm:"column:is_active;type:boolean;not null;index:idx_pricing_match,priority:3;default:true" json:"is_active"`
	Priority          *int32          `gorm:"column:priority;type:integer;not null;index:idx_pricing_match,priority:7;default:0;comment:规则优先级（用于匹配冲突时选择）" json:"priority"` // 规则优先级（用于匹配冲突时选择）
	CreatedAt         time.Time       `gorm:"column:created_at;type:timestamp with time zone;not null" json:"created_at"`
	UpdatedAt         time.Time       `gorm:"column:updated_at;type:timestamp with time zone;not null" json:"updated_at"`
}

// TableName PricingRule's table name
func (*PricingRule) TableName() string {
	return TableNamePricingRule
}
