// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameSocialAccount = "public.social_accounts"

// SocialAccount mapped from table <public.social_accounts>
type SocialAccount struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Provider        string     `gorm:"column:provider;type:character varying(16);not null;uniqueIndex:idx_social_provider_subject,priority:1" json:"provider"`
	ProviderSubject string     `gorm:"column:provider_subject;type:character varying(255);not null;uniqueIndex:idx_social_provider_subject,priority:2" json:"provider_subject"`
	UserID          int64      `gorm:"column:user_id;type:bigint;not null;index:idx_social_accounts_user_id,priority:1" json:"user_id"`
	Email           *string    `gorm:"column:email;type:character varying(100)" json:"email"`
	CreatedAt       *time.Time `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt       *time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
}

// TableName SocialAccount's table name
func (*SocialAccount) TableName() string {
	return TableNameSocialAccount
}
