// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSpatialRefSy = "public.spatial_ref_sys"

// SpatialRefSy mapped from table <public.spatial_ref_sys>
type SpatialRefSy struct {
	Srid      int32   `gorm:"column:srid;type:integer;primaryKey" json:"srid"`
	AuthName  *string `gorm:"column:auth_name;type:character varying(256)" json:"auth_name"`
	AuthSrid  *int32  `gorm:"column:auth_srid;type:integer" json:"auth_srid"`
	Srtext    *string `gorm:"column:srtext;type:character varying(2048)" json:"srtext"`
	Proj4text *string `gorm:"column:proj4text;type:character varying(2048)" json:"proj4text"`
}

// TableName SpatialRefSy's table name
func (*SpatialRefSy) TableName() string {
	return TableNameSpatialRefSy
}
