// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUser = "public.users"

// User mapped from table <public.users>
type User struct {
	ID           int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Email        string     `gorm:"column:email;type:character varying(100);not null;uniqueIndex:uniq_users_email,priority:1;comment:邮箱（允许空字符串，非空时唯一）" json:"email"` // 邮箱（允许空字符串，非空时唯一）
	Phone        string     `gorm:"column:phone;type:character varying(30);not null;uniqueIndex:uniq_users_phone,priority:1;comment:手机号（允许空字符串，非空时唯一）" json:"phone"` // 手机号（允许空字符串，非空时唯一）
	PasswordHash string     `gorm:"column:password_hash;type:character varying(255);not null;comment:密码哈希" json:"password_hash"`                                     // 密码哈希
	Nickname     string     `gorm:"column:nickname;type:character varying(50);not null;comment:昵称" json:"nickname"`                                                  // 昵称
	Status       *int16     `gorm:"column:status;type:smallint;not null;index:idx_users_status,priority:1;default:1;comment:状态：1正常 2封禁" json:"status"`               // 状态：1正常 2封禁
	StatusReason string     `gorm:"column:status_reason;type:character varying(255);not null;comment:封禁原因/状态说明" json:"status_reason"`                                // 封禁原因/状态说明
	CreatedAt    time.Time  `gorm:"column:created_at;type:timestamp with time zone;not null" json:"created_at"`
	LastLoginAt  *time.Time `gorm:"column:last_login_at;type:timestamp with time zone;comment:最后登录时间" json:"last_login_at"`               // 最后登录时间
	UpdatedAt    time.Time  `gorm:"column:updated_at;type:timestamp with time zone;not null;comment:更新时间（无触发器，需应用层更新）" json:"updated_at"` // 更新时间（无触发器，需应用层更新）
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
