// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameZipCode = "public.zip_codes"

// ZipCode mapped from table <public.zip_codes>
type ZipCode struct {
	ZipCode     string     `gorm:"column:zip_code;type:character varying(10);primaryKey;index:idx_zip_codes_zip_prefix,priority:1;comment:ZIP 邮编（主键）" json:"zip_code"`                      // ZIP 邮编（主键）
	City        string     `gorm:"column:city;type:character varying(100);not null;index:idx_zip_codes_city,priority:1;index:idx_zip_codes_state_city,priority:1;comment:城市名称" json:"city"` // 城市名称
	StateCode   string     `gorm:"column:state_code;type:character(2);not null;index:idx_zip_codes_state_city,priority:2;comment:州缩写，例如 CA / NY" json:"state_code"`                         // 州缩写，例如 CA / NY
	StateName   string     `gorm:"column:state_name;type:character varying(100);not null;comment:州完整名称，例如 California" json:"state_name"`                                                    // 州完整名称，例如 California
	Lat         float64    `gorm:"column:lat;type:double precision;not null;comment:纬度" json:"lat"`                                                                                         // 纬度
	Lng         float64    `gorm:"column:lng;type:double precision;not null;comment:经度" json:"lng"`                                                                                         // 经度
	Location    *string    `gorm:"column:location;type:geometry(Point,4326);index:idx_zip_codes_location,priority:1;comment:PostGIS 地理点（SRID=4326），用于距离查询" json:"location"`                 // PostGIS 地理点（SRID=4326），用于距离查询
	Population  *int32     `gorm:"column:population;type:integer;default:0;comment:ZIP 区域人口" json:"population"`                                                                             // ZIP 区域人口
	Density     *float64   `gorm:"column:density;type:double precision;default:0;comment:人口密度" json:"density"`                                                                              // 人口密度
	CountyFips  *string    `gorm:"column:county_fips;type:character varying(20);comment:County FIPS 编码" json:"county_fips"`                                                                 // County FIPS 编码
	CountyName  *string    `gorm:"column:county_name;type:character varying(100);comment:County 名称" json:"county_name"`                                                                     // County 名称
	Timezone    *string    `gorm:"column:timezone;type:character varying(50);index:idx_zip_codes_timezone,priority:1;comment:时区，例如 America/Los_Angeles" json:"timezone"`                    // 时区，例如 America/Los_Angeles
	IsImprecise *bool      `gorm:"column:is_imprecise;type:boolean;default:false;comment:是否为低精度 ZIP（估算中心点）" json:"is_imprecise"`                                                            // 是否为低精度 ZIP（估算中心点）
	IsMilitary  *bool      `gorm:"column:is_military;type:boolean;default:false;comment:是否为军用 ZIP" json:"is_military"`                                                                      // 是否为军用 ZIP
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                                                          // 创建时间
}

// TableName ZipCode's table name
func (*ZipCode) TableName() string {
	return TableNameZipCode
}
