// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Package logic imports all business logic implementations so their init
// functions can register implementations with the generated service package.
package logic

import _ "github.com/lanechi/gonex/examples/quick-demo/internal/logic/testservice"
