// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"github.com/lanechi/gonex/examples/quick-demo/internal/model"
)

type ITestservice interface {
	Create(ctx context.Context, input *model.TestModel) (*model.TestModel, error)
	Delete(_ context.Context, _ *model.TestModel) (*model.TestModel, error)
	GetList(_ context.Context, _ *model.TestModel) (*model.TestModelList, error)
	GetOne(_ context.Context, _ *model.TestModel) (*model.TestModel, error)
	Update(_ context.Context, _ *model.TestModel) (*model.TestModel, error)
}

var localTestservice ITestservice

// Testservice returns the registered Testservice service implementation.
func Testservice() ITestservice {
	if localTestservice == nil {
		panic("gx: testservice service is not registered")
	}
	return localTestservice
}

// RegisterTestservice registers the Testservice service implementation.
func RegisterTestservice(implementation ITestservice) {
	localTestservice = implementation
}
