// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAdminGroup = "admin.admin_group"

// AdminGroup mapped from table <admin.admin_group>
type AdminGroup struct {
	ID        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                               // 主键ID
	Name      string     `gorm:"column:name;type:character varying(64);not null;uniqueIndex:idx_admin_group_name,priority:1;comment:角色名称（唯一）" json:"name"` // 角色名称（唯一）
	Nodes     []string   `gorm:"column:nodes;type:text[];not null;default:{};comment:权限节点 JSON 数组" json:"nodes"`                                           // 权限节点 JSON 数组
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                           // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                                           // 更新时间
}

// TableName AdminGroup's table name
func (*AdminGroup) TableName() string {
	return TableNameAdminGroup
}
