// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAdmin = "admin.admin"

// Admin mapped from table <admin.admin>
type Admin struct {
	ID          int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                      // 主键ID
	Username    string     `gorm:"column:username;type:character varying(64);not null;uniqueIndex:idx_admin_username,priority:1;comment:登录用户名（唯一）" json:"username"` // 登录用户名（唯一）
	Password    string     `gorm:"column:password;type:character varying(255);not null;comment:登录密码（bcrypt）" json:"password"`                                       // 登录密码（bcrypt）
	Email       string     `gorm:"column:email;type:character varying(64);not null;comment:管理员邮箱" json:"email"`                                                     // 管理员邮箱
	Secret      string     `gorm:"column:secret;type:character varying(50);not null;comment:二次验证密钥（2FA）" json:"secret"`                                             // 二次验证密钥（2FA）
	GroupID     *int64     `gorm:"column:group_id;type:bigint;not null;index:idx_admin_group_id,priority:1;default:1;comment:管理员角色组ID" json:"group_id"`             // 管理员角色组ID
	Status      *bool      `gorm:"column:status;type:boolean;not null;index:idx_admin_status,priority:1;default:true;comment:状态：1启用 0禁用" json:"status"`             // 状态：1启用 0禁用
	Tel         string     `gorm:"column:tel;type:character varying(50);not null;comment:联系电话" json:"tel"`                                                          // 联系电话
	Gender      *int16     `gorm:"column:gender;type:smallint;not null;default:0;comment:性别：0未知 1男 2女" json:"gender"`                                               // 性别：0未知 1男 2女
	Remark      string     `gorm:"column:remark;type:character varying(50);not null;comment:备注信息" json:"remark"`                                                    // 备注信息
	LastLoginIP string     `gorm:"column:last_login_ip;type:character varying(45);not null;comment:最后登录IP" json:"last_login_ip"`                                    // 最后登录IP
	LastLoginAt *time.Time `gorm:"column:last_login_at;type:timestamp with time zone;comment:最后登录时间" json:"last_login_at"`                                          // 最后登录时间
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                                  // 创建时间
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                                                  // 更新时间
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
