// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameEmailTemplate = "admin.email_template"

// EmailTemplate mapped from table <admin.email_template>
type EmailTemplate struct {
	ID        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Code      string     `gorm:"column:code;type:character varying(64);not null;uniqueIndex:idx_email_template_code,priority:1" json:"code"`
	Name      string     `gorm:"column:name;type:character varying(100);not null" json:"name"`
	Title     string     `gorm:"column:title;type:character varying(255);not null" json:"title"`
	Content   string     `gorm:"column:content;type:text;not null" json:"content"`
	Status    *bool      `gorm:"column:status;type:boolean;not null;index:idx_email_template_status,priority:1;default:true" json:"status"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
}

// TableName EmailTemplate's table name
func (*EmailTemplate) TableName() string {
	return TableNameEmailTemplate
}
