// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameFileAsset = "admin.file_assets"

// FileAsset mapped from table <admin.file_assets>
type FileAsset struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_file_assets_processed,priority:1" json:"id"`
	ImageType       *int16    `gorm:"column:image_type;type:smallint;not null;index:idx_file_assets_image_type,priority:1;default:0" json:"image_type"`
	ObjectKey       string    `gorm:"column:object_key;type:character varying(255);not null;uniqueIndex:idx_file_assets_object_key,priority:1;comment:R2 key 或者 AWS S3 key" json:"object_key"`              // R2 key 或者 AWS S3 key
	ThumbObjectKey  string    `gorm:"column:thumb_object_key;type:character varying(255);not null;comment:缩略图对象键" json:"thumb_object_key"`                                                                  // 缩略图对象键
	FileName        string    `gorm:"column:file_name;type:character varying(255);not null;comment:文件名" json:"file_name"`                                                                                   // 文件名
	EndPoint        string    `gorm:"column:end_point;type:character varying(500);not null;comment:CDN URL" json:"end_point"`                                                                               // CDN URL
	FileMd5         string    `gorm:"column:file_md5;type:character varying(32);not null;index:idx_file_assets_file_md5,priority:1;comment:文件MD5" json:"file_md5"`                                          // 文件MD5
	FileSize        int64     `gorm:"column:file_size;type:bigint;not null;comment:文件大小" json:"file_size"`                                                                                                  // 文件大小
	Platform        *int16    `gorm:"column:platform;type:smallint;not null;index:idx_file_assets_platform,priority:1;default:0;comment:存储平台 0 =本地 , 1 =R2 , 2 = aws 3 = oracle 4 = other" json:"platform"` // 存储平台 0 =本地 , 1 =R2 , 2 = aws 3 = oracle 4 = other
	MimeType        *string   `gorm:"column:mime_type;type:character varying(50);not null;default:image/webp;comment:MIME 类型" json:"mime_type"`                                                             // MIME 类型
	TempPath        string    `gorm:"column:temp_path;type:character varying(500);not null;comment:临时文件路径（仅上传中存在，上传完成后清空）" json:"temp_path"`                                                                // 临时文件路径（仅上传中存在，上传完成后清空）
	IsProcessed     *bool     `gorm:"column:is_processed;type:boolean;not null;index:idx_file_assets_processed,priority:2;default:false;comment:是否已处理" json:"is_processed"`                                 // 是否已处理
	Processing      *bool     `gorm:"column:processing;type:boolean;not null;index:idx_file_assets_processed,priority:3;default:false;comment:是否正在处理" json:"processing"`                                    // 是否正在处理
	ProcessAttempts *int32    `gorm:"column:process_attempts;type:integer;not null;default:0;comment:处理尝试次数" json:"process_attempts"`                                                                       // 处理尝试次数
	ProcessError    *string   `gorm:"column:process_error;type:text;comment:处理错误信息" json:"process_error"`                                                                                                   // 处理错误信息
	OwnerType       *int16    `gorm:"column:owner_type;type:smallint;not null;index:idx_file_assets_owner,priority:2;default:0;comment:所有者类型 0 = user, 1 = admin 3 = system" json:"owner_type"`             // 所有者类型 0 = user, 1 = admin 3 = system
	OwnerID         *int64    `gorm:"column:owner_id;type:bigint;not null;index:idx_file_assets_owner,priority:1;default:0;comment:所有者ID" json:"owner_id"`                                                  // 所有者ID
	IsVerified      *bool     `gorm:"column:is_verified;type:boolean;not null;index:idx_file_assets_is_verified,priority:1;default:false;comment:是否已验证" json:"is_verified"`                                 // 是否已验证
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_file_assets_created_at,priority:1" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;index:idx_file_assets_updated,priority:1" json:"updated_at"`
}

// TableName FileAsset's table name
func (*FileAsset) TableName() string {
	return TableNameFileAsset
}
