// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameLog = "admin.logs"

// Log mapped from table <admin.logs>
type Log struct {
	ID            int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	AdminID       int64      `gorm:"column:admin_id;type:bigint;not null;index:idx_logs_admin_id,priority:1" json:"admin_id"`
	IPAddress     string     `gorm:"column:ip_address;type:character varying(45);not null" json:"ip_address"`
	Ua            string     `gorm:"column:ua;type:text;not null" json:"ua"`
	RequestPath   string     `gorm:"column:request_path;type:character varying(255);not null" json:"request_path"`
	RequestMethod string     `gorm:"column:request_method;type:character varying(10);not null" json:"request_method"`
	RequestData   string     `gorm:"column:request_data;type:text;not null" json:"request_data"`
	Result        *bool      `gorm:"column:result;type:boolean;not null;index:idx_logs_result,priority:1;default:false" json:"result"`
	ErrorMessage  string     `gorm:"column:error_message;type:text;not null" json:"error_message"`
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp with time zone;index:idx_logs_created_at,priority:1" json:"created_at"`
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
}

// TableName Log's table name
func (*Log) TableName() string {
	return TableNameLog
}
