// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameMenu = "admin.menu"

// Menu mapped from table <admin.menu>
type Menu struct {
	ID            int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                              // 主键ID
	Pid           *int64     `gorm:"column:pid;type:bigint;uniqueIndex:idx_menu_pid_name,priority:2;index:idx_menu_pid,priority:1;default:0;comment:父级菜单ID（0为顶级）" json:"pid"` // 父级菜单ID（0为顶级）
	Name          string     `gorm:"column:name;type:character varying(50);not null;uniqueIndex:idx_menu_pid_name,priority:1;comment:前端路由名称" json:"name"`                     // 前端路由名称
	Path          string     `gorm:"column:path;type:character varying(255);not null;comment:路由访问路径" json:"path"`                                                             // 路由访问路径
	Title         string     `gorm:"column:title;type:character varying(100);not null;comment:菜单显示标题" json:"title"`                                                           // 菜单显示标题
	RequiresAuth  *bool      `gorm:"column:requires_auth;type:boolean;not null;default:true;comment:是否需要登录鉴权" json:"requires_auth"`                                           // 是否需要登录鉴权
	Icon          string     `gorm:"column:icon;type:character varying(100);not null;comment:菜单图标" json:"icon"`                                                               // 菜单图标
	MenuType      *string    `gorm:"column:menu_type;type:character varying(20);not null;index:idx_menu_type,priority:1;default:page;comment:菜单类型" json:"menu_type"`          // 菜单类型
	Href          string     `gorm:"column:href;type:character varying(255);not null;comment:外链地址" json:"href"`                                                               // 外链地址
	ComponentPath string     `gorm:"column:component_path;type:character varying(255);not null;comment:前端组件路径" json:"component_path"`                                         // 前端组件路径
	Sort          *int32     `gorm:"column:sort;type:integer;not null;index:idx_menu_sort,priority:1;default:0;comment:排序值" json:"sort"`                                      // 排序值
	WithoutTab    *bool      `gorm:"column:without_tab;type:boolean;not null;default:false;comment:是否显示在标签页" json:"without_tab"`                                              // 是否显示在标签页
	PinTab        *bool      `gorm:"column:pin_tab;type:boolean;not null;default:false;comment:是否固定标签页" json:"pin_tab"`                                                       // 是否固定标签页
	ActiveMenu    string     `gorm:"column:active_menu;type:character varying(255);not null;comment:是否高亮父菜单" json:"active_menu"`                                              // 是否高亮父菜单
	KeepAlive     *bool      `gorm:"column:keep_alive;type:boolean;not null;default:false;comment:是否缓存" json:"keep_alive"`                                                    // 是否缓存
	Hide          *bool      `gorm:"column:hide;type:boolean;not null;default:false;comment:是否隐藏" json:"hide"`                                                                // 是否隐藏
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                                          // 创建时间
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                                                          // 更新时间
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
