// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameMessage = "admin.messages"

// Message mapped from table <admin.messages>
type Message struct {
	ID          int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UID         int64      `gorm:"column:uid;type:bigint;not null;index:idx_messages_uid,priority:1;index:idx_messages_uid_is_read,priority:2" json:"uid"`
	Title       string     `gorm:"column:title;type:character varying(255);not null" json:"title"`
	Content     string     `gorm:"column:content;type:text;not null" json:"content"`
	MsgType     *int16     `gorm:"column:msg_type;type:smallint;not null;default:0" json:"msg_type"`
	IsRead      *int16     `gorm:"column:is_read;type:smallint;not null;index:idx_messages_uid_is_read,priority:1;default:0" json:"is_read"`
	ReferenceID string     `gorm:"column:reference_id;type:character varying(64);not null" json:"reference_id"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
