// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"encoding/json"
	"time"
)

const TableNameQueue = "admin.queue"

// Queue mapped from table <admin.queue>
type Queue struct {
	ID           int64           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Type         string          `gorm:"column:type;type:text;not null" json:"type"`
	Payload      json.RawMessage `gorm:"column:payload;type:jsonb;not null" json:"payload"`
	Status       *string         `gorm:"column:status;type:text;not null;index:idx_job_pending,priority:2;default:pending" json:"status"`
	RetryCount   *int32          `gorm:"column:retry_count;type:integer;not null;default:0" json:"retry_count"`
	MaxRetries   *int32          `gorm:"column:max_retries;type:integer;not null;default:3" json:"max_retries"`
	NextRunAt    *time.Time      `gorm:"column:next_run_at;type:timestamp with time zone;not null;index:idx_job_pending,priority:1;default:now()" json:"next_run_at"`
	LockedAt     *time.Time      `gorm:"column:locked_at;type:timestamp with time zone" json:"locked_at"`
	LockedBy     *string         `gorm:"column:locked_by;type:text" json:"locked_by"`
	ErrorMessage *string         `gorm:"column:error_message;type:text" json:"error_message"`
	CreatedAt    time.Time       `gorm:"column:created_at;type:timestamp with time zone;not null" json:"created_at"`
	UpdatedAt    time.Time       `gorm:"column:updated_at;type:timestamp with time zone;not null" json:"updated_at"`
}

// TableName Queue's table name
func (*Queue) TableName() string {
	return TableNameQueue
}
