// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTasksLog = "admin.tasks_logs"

// TasksLog mapped from table <admin.tasks_logs>
type TasksLog struct {
	ID             int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TaskID         int64      `gorm:"column:task_id;type:bigint;not null;index:idx_tasks_logs_task_time,priority:2" json:"task_id"`
	ExecuteTime    time.Time  `gorm:"column:execute_time;type:timestamp with time zone;not null;index:idx_tasks_logs_task_time,priority:1" json:"execute_time"`
	DurationMs     int64      `gorm:"column:duration_ms;type:bigint;not null" json:"duration_ms"`
	Success        int16      `gorm:"column:success;type:smallint;not null" json:"success"`
	ErrorMsg       string     `gorm:"column:error_msg;type:text;not null" json:"error_msg"`
	CallbackResult string     `gorm:"column:callback_result;type:text;not null" json:"callback_result"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
}

// TableName TasksLog's table name
func (*TasksLog) TableName() string {
	return TableNameTasksLog
}
