// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"encoding/json"
	"time"
)

const TableNameTask = "admin.tasks"

// Task mapped from table <admin.tasks>
type Task struct {
	ID          int64           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string          `gorm:"column:name;type:character varying(100);not null" json:"name"`
	CronType    *int16          `gorm:"column:cron_type;type:smallint;not null;default:0" json:"cron_type"`
	CronExpr    string          `gorm:"column:cron_expr;type:character varying(50);not null" json:"cron_expr"`
	Times       *int32          `gorm:"column:times;type:integer;not null;default:0" json:"times"`
	IsEnabled   *bool           `gorm:"column:is_enabled;type:boolean;not null;index:idx_tasks_enabled,priority:1;default:true" json:"is_enabled"`
	CallbackURL string          `gorm:"column:callback_url;type:character varying(255);not null" json:"callback_url"`
	Params      json.RawMessage `gorm:"column:params;type:jsonb;not null;default:{}" json:"params"`
	HandlerName string          `gorm:"column:handler_name;type:character varying(100);not null" json:"handler_name"`
	CreatedAt   *time.Time      `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt   *time.Time      `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
