// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
)

type IHello interface {
	Greet(_ context.Context, name string) string
}

var localHello IHello

// Hello returns the registered Hello service implementation.
func Hello() IHello {
	if localHello == nil {
		panic("gx: hello service is not registered")
	}
	return localHello
}

// RegisterHello registers the Hello service implementation.
func RegisterHello(implementation IHello) {
	localHello = implementation
}
