// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

package model

// TestModel is the placeholder request and response model used by generated
// demo services. Replace it with business-specific models as the project grows.
type TestModel struct {
	ID   int64  `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

// TestModelList is the non-paginated list response model for demo services.
type TestModelList struct {
	Items []*TestModel `json:"items"`
}

// TestModelPage is the paginated list response model for demo services.
type TestModelPage struct {
	Items    []*TestModel `json:"items"`
	Page     int          `json:"page"`
	PageSize int          `json:"pageSize"`
	Total    int64        `json:"total"`
}
