// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import _ "github.com/lanechi/gonex/examples/demo/internal/logic/hello"
