// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

package hello

type ControllerV1 struct{}

func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
