// ==========================================================================
// Code generated by Gonex CLI tool. DO NOT EDIT.
// ==========================================================================

package user

import (
	"context"
	"github.com/lanechi/gonex/examples/quick-demo/api/user/v1"
)

type IUserV1 interface {
	CreateUser(ctx context.Context, req *v1.CreateUserReq) (*v1.CreateUserRes, error)
	DeleteUser(ctx context.Context, req *v1.DeleteUserReq) (*v1.DeleteUserRes, error)
	GetListUser(ctx context.Context, req *v1.GetListUserReq) (*v1.GetListUserRes, error)
	GetOneUser(ctx context.Context, req *v1.GetOneUserReq) (*v1.GetOneUserRes, error)
	UpdateUser(ctx context.Context, req *v1.UpdateUserReq) (*v1.UpdateUserRes, error)
}
type ControllerV1 struct {
}

func NewV1() *ControllerV1 {
	return &ControllerV1{}
}
